import fs from 'fs';
import path from 'path';
import { randomBytes } from 'crypto';
import { getTongoNetworkConfig } from '../src/tongo-config';

const root = process.cwd();
const envPath = path.join(root, '.env');
const templatePath = path.join(root, 'env.example');

function generateTongoKey(): string {
  return '0x' + randomBytes(32).toString('hex');
}

function main() {
  if (fs.existsSync(envPath)) {
    console.error('⚠️ .env already exists. Aborting to avoid overwriting.');
    process.exit(1);
  }

  const network = (process.env.TONGO_NETWORK || 'sepolia') as 'sepolia' | 'mainnet';
  const config = getTongoNetworkConfig(network);

  const base = fs.existsSync(templatePath)
    ? fs.readFileSync(templatePath, 'utf-8')
    : '';

  const tongoKey = generateTongoKey();

  const content = [
    '# Generated by tongo-init',
    `TONGO_NETWORK=${network}`,
    `STARKNET_RPC_URL=${config.rpcUrl}`,
    'STARKNET_ACCOUNT_ADDRESS=0xYOUR_ACCOUNT',
    'STARKNET_PRIVATE_KEY=0xYOUR_STARKNET_PRIVATE_KEY',
    `TONGO_PRIVATE_KEY=${tongoKey}`,
    `TONGO_CONTRACT_ADDRESS=${config.tongoContractAddress}`,
    `STRK_ADDRESS=${config.strkAddress}`,
    '',
    '# Optional',
    'TEST_TOKEN_AMOUNT=1.0',
    'TEST_RECIPIENT_PUBLIC_KEY=',
    'TEST_ENABLE_RAGEQUIT=false',
    '',
  ].join('\n');

  fs.writeFileSync(envPath, content, 'utf-8');

  console.log('✅ .env created');
  console.log(`Network: ${config.name}`);
  console.log('Tongo private key generated and saved to .env');
  console.log('Next: fill STARKNET_ACCOUNT_ADDRESS and STARKNET_PRIVATE_KEY');
}

main();
